#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned RP;
typedef unsigned RO;
typedef unsigned long long ULL;
typedef U  GateCount;
typedef U  NodeCount;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef struct {
    U  I667;
    RP  I668;
} RmaReceiveClock1;
typedef NodeCount  FlatNodeNum;
typedef U  InstNum;
typedef unsigned long long TimeStamp64;
typedef U  TimeStamp;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef union {
    double I687;
    unsigned long long I688;
    unsigned  I689[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    struct eblk * I696;
    E_fn  I697;
    struct iptmpl * I698;
    unsigned I700;
    struct eblk * I701;
} eblk_struct;
typedef struct {
    RP  I696;
    RP  I697;
    RP  I698;
    unsigned I700;
    RP  I701;
} RmaEblk;
typedef union {
    double I687;
    unsigned long long I688;
    unsigned  I689[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I737;
    RmaEblk  I695;
    U  I738;
    US  I739 :1;
    US  I740 :4;
    US  I178 :2;
    US  state :2;
    US  I742 :1;
    US  I743 :2;
    US  I744 :2;
    US  fHsim :1;
    US  I550 :1;
    scalar  newval;
    scalar  I746;
    RP  I747;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I727;
    scalar  I728;
    scalar  I729;
    scalar  I730;
    scalar  fHsim :1;
    scalar  I178 :6;
    U  I732;
    EBLK  I733;
    void * I734;
    UP   I735[1];
};
struct RmaMPSched {
    RP  I727;
    scalar  I728;
    scalar  I729;
    scalar  I730;
    scalar  fHsim :1;
    scalar  I178 :6;
    U  I732;
    RmaEblk  I733;
    RP  I734;
    RP   I735[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I727;
    scalar  I728;
    scalar  I729;
    scalar  I730;
    scalar  I178;
    U  I732;
    RmaEblk  I733;
    scalar  I744;
    scalar  I751;
    scalar  I752;
    scalar  I753;
    U  I754;
    RmaClockStruct  I755;
    RmaClockStruct  I756;
    U  state;
    U  I757;
    RP  I698;
    RP  I758;
    RP  I759;
    RP   I735[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I761;
    void * I762;
};
typedef struct {
    RmaEblk  I695;
    RP  I763;
    scalar  I764;
    scalar  I744;
    scalar  I765;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I727;
    scalar  I728;
    scalar  I729;
    scalar  I730;
    scalar  fHsim :1;
    scalar  I178 :6;
    U  I732;
    RmaEblk  I733;
    scalar  I744;
    scalar  I751;
    scalar  I752;
    scalar  I753;
    U  state :4;
    U  I767 :28;
    RmaClockStruct  I755;
    RmaClockStruct  I756;
    RP  I768;
    RP  I698;
    RP  I769;
    RP   I735[1];
};
typedef struct red_t {
    U  I770;
    U  I771;
    U  I650;
} RED;
typedef struct predd {
    PD_e  I178;
    RED   I772[0];
} PREDD;
union rhs_value {
    vec32  I773;
    scalar  I764;
    vec32  * I744;
    double I774;
    U  I775;
};
typedef struct nbs_t {
    struct nbs_t * I776;
    struct nbs_t * I778;
    void (* I779)(struct nbs_t * I780);
    unsigned I781 :1;
    unsigned I782 :1;
    unsigned I783 :1;
    unsigned I784 :1;
    unsigned I785 :27;
    void * I786;
    U  I787;
    union rhs_value I788;
    vec32  I687;
    union {
        struct nbs_t * first;
        struct nbs_t * last;
    } I790;
} NBS;
typedef struct {
    RP  I791;
    RP  I758;
    RP  I698;
    RP  I759;
    RmaEblk  I695;
    RmaEblk  I792;
    RP  I793;
    scalar  I764;
    scalar  I744;
    char state;
    uscope_t  I794;
    U  I795;
    RP  I796;
    scalar  I751;
    scalar  I752;
    scalar  I753;
    RmaClockStruct  I755;
    RmaClockStruct  I756;
    RP  I734;
} RmaPulse;
typedef struct {
    int * I797;
    long long I798;
} TypeData;
struct etype {
    U  I566 :8;
    U  I567 :24;
    U  I568;
    U  I569 :1;
    U  I570 :1;
    U  I571 :1;
    U  I572 :1;
    U  I573 :1;
    U  I574 :1;
    U  I575 :1;
    U  I576 :1;
    U  I577 :1;
    U  I578 :4;
    U  I579 :1;
    U  I580 :1;
    U  I581 :1;
    U  I582 :1;
    U  I583 :1;
    U  I584 :1;
    U  I585 :1;
    U  I586 :1;
    U  I587 :2;
    U  I588 :1;
    U  I589 :2;
    U  I590 :1;
    U  I591 :1;
    U  I592 :1;
    U  I593 :1;
    U  I594 :2;
    TypeData  * I595;
    U  I596;
    U  I597;
    U  I598 :1;
    U  I599 :1;
    U  I600 :1;
    U  I601 :1;
    U  I602 :2;
    U  I603 :2;
    U  I604 :1;
    U  I605 :1;
    U  I606 :1;
    U  I607 :1;
    U  I608 :1;
    U  I609 :1;
    U  I610 :1;
    U  I611 :1;
    U  I612 :16;
};
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I802 :1;
    U  I803 :1;
    U  I804 :1;
    U  I805 :1;
    U  I806 :1;
    U  I807 :1;
    U  I808 :1;
    U  I809 :1;
    U  I810 :1;
    U  I811 :1;
    U  I812 :1;
    U  I813 :1;
    U  I814 :1;
    U  I815 :1;
    U  I816 :1;
    U  I817 :1;
    U  I818 :1;
    U  I819 :1;
    QIRDModuleType  I820 :2;
    U  I821 :1;
    U  I822 :1;
    U  I823 :1;
    U  I824 :1;
    U  I825 :1;
    U  I826 :1;
    U  I827 :1;
    U  I828 :1;
    U  I829 :1;
    U  I830 :1;
    U  I831 :1;
    U  I832 :1;
    U  I833 :1;
    U  I834 :1;
    U  I835 :1;
    U  I836 :1;
    U  I837 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    UP  * I20;
    U  I21;
    UP  * I22;
    U  I23;
    U  I24;
    U  I25;
    U  * I26;
    U  * I27;
    void * I28;
    void * I29;
    U  I30;
    int I31;
    UP  I32;
    U  I33;
    U  I34;
    U  I35;
    UP  I36;
    U  * I37;
    BitFlags  I38;
    U  I39;
    U  I40;
    U  I41;
    U  I42;
    U  I43;
    U  * I44;
    U  I45;
    U  * I46;
    U  I47;
    U  I48;
    U  I49;
    U  I50;
    U  I51;
    U  I52;
    U  I53;
    U  * I54;
    U  * I55;
    U  I56;
    U  I57;
    U  * I58;
    U  I59;
    U  * I60;
    U  I61;
    U  I62;
    U  I63;
    U  I64;
    U  * I65;
    U  I66;
    U  * I67;
    U  I68;
    U  I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  * I74;
    char * I75;
    U  I76;
    U  I77;
    U  I78;
    U  I79;
    U  I80;
    U  * I81;
    U  I82;
    U  I83;
    UP  * I84;
    U  I85;
    U  I86;
    UP  * I87;
    U  I88;
    U  I89;
    U  I90;
    U  I91;
    U  I92;
    U  I93;
    U  * I94;
    U  I95;
    U  I96;
    U  * I97;
    U  * I98;
    U  * I99;
    U  * I100;
    U  * I101;
    U  I102;
    U  I103;
    struct taskInfo * I104;
    U  I106;
    U  I107;
    int * I108;
    UP  * I109;
    U  * I110;
    U  I111;
    U  I112;
    U  I113;
    U  I114;
    U  I115;
    struct qrefer * I116;
    U  * I118;
    unsigned * I119;
    void * I120;
    U  I121;
    U  I122;
    struct classStaticReferData * I123;
    U  I125;
    U  * I126;
    U  I127;
    U  I128;
    U  I129;
    U  * I130;
    U  I131;
    U  * I132;
    U  I133;
    U  I134;
    U  I135;
    U  * I136;
    U  I137;
    U  * I138;
    U  I139;
    U  I140;
    U  * I141;
    U  I142;
    U  I143;
    U  * I144;
    U  * I145;
    U  * I146;
    U  I147;
    U  I148;
    U  I149;
    U  I150;
    U  I151;
    struct qrefee * I152;
    U  * I154;
    U  I155;
    struct qdefrefee * I156;
    U  * I158;
    int (* I159)(void);
    char * I160;
    U  I161;
    U  I162;
    void * I163;
    void * I164;
    NumLibs_t  I165;
    char * I166;
    U  * I167;
    U  I168;
    U  I169;
    U  I170;
    U  I171;
    U  I172;
    U  * I173;
    U  * I174;
    int I175;
    struct clock_load * I176;
    int I191;
    struct clock_data * I192;
    int I208;
    struct clock_hiconn * I209;
    U  I213;
    int I214;
    U  I215;
    int I216;
    U  * I217;
    U  * I218;
    U  I219;
    void * I220;
    U  I221;
    U  I222;
    UP  * I223;
    void * I224;
    U  I225;
    UP  * I226;
    U  * I227;
    int (* I228)(void);
    U  * I229;
    UP  * I230;
    U  * I231;
    U  I232 :1;
    U  I233 :31;
    U  I234;
    U  I235;
    UP  * I236;
    U  * I237;
    U  I238 :1;
    U  I239 :1;
    U  I240 :1;
    U  I241 :1;
    U  I242 :28;
    U  I243;
    U  I244;
    U  I245;
    U  I246 :31;
    U  I247 :1;
    UP  * I248;
    UP  * I249;
    U  * I250;
    U  * I251;
    U  * I252;
    UP  * I253;
    UP  * I254;
    UP  * I255;
    U  * I256;
    UP  * I257;
    UP  * I258;
    UP  * I259;
    char * I260;
    U  I261;
    U  I262;
    U  I263;
    UP  * I264;
    UP  * I265;
    UP  * I266;
    UP  * I267;
    UP  * I268;
    UP  * I269;
    UP  * I270;
    UP  * I271;
    UP  * I272;
    UP  * I273;
    UP  * I274;
    UP  * I275;
    UP  * I276;
    U  * I277;
    U  * I278;
    UP  * I279;
    U  I280;
    U  I281;
    U  I282;
    U  I283;
    U  I284;
    U  I285;
    U  I286;
    U  I287;
    char * I288;
    U  * I289;
    U  I290;
    U  I291;
    U  I292;
    U  I293;
    U  I294;
    UP  * I295;
    UP  * I296;
    UP  * I297;
    UP  * I298;
    struct daidirInfo * I299;
    struct vcs_tftable * I301;
    U  I303;
    UP  * I304;
    UP  * I305;
    U  I306;
    U  I307;
    U  I308;
    UP  * I309;
    U  * I310;
    struct qird_hil_data * I311;
    UP  (* I313)(void);
    UP  (* I314)(void);
    UP  (* I315)(void);
    UP  (* I316)(void);
    UP  (* I317)(void);
    int * I318;
    int (* I319)(void);
    char * I320;
    UP  * I321;
    UP  * I322;
    UP  (* I323)(void);
    int (* I324)(void);
    int * I325;
    int (* I326)(void);
    int * I327;
    char * I328;
    U  * I329;
    U  * I330;
    U  * I331;
    U  * I332;
    void * I333;
    U  I334;
    void * I335;
    U  I336;
    U  I337;
    U  I338;
    U  I339;
    U  I340;
    U  I341;
    UP  * I342;
    U  * I343;
    U  * I344;
    U  I345 :15;
    U  I346 :14;
    U  I347 :1;
    U  I348 :1;
    U  I349 :1;
    U  I350 :3;
    U  I351 :1;
    U  I352 :1;
    U  I353 :17;
    U  I354 :3;
    U  I355 :5;
    U  I356 :2;
    U  I357 :1;
    U  I358 :31;
    struct scope * I359;
    U  I361;
    U  I362;
    U  I363;
    U  * I364;
    U  * I365;
    U  * I366;
    U  I367;
    U  I368;
    U  I369;
    struct pcbt * I370;
    U  I380;
    U  I381;
    U  I382;
    U  I383;
    void * I384;
    void * I385;
    void * I386;
    int I387;
    U  * I388;
    U  I389;
    U  I390;
    U  I391;
    U  I392;
    U  I393;
    U  I394;
    U  I395;
    void * I396;
    UP  * I397;
    U  I398;
    U  I399;
    void * I400;
    U  I401;
    void * I402;
    U  I403;
    void * I404;
    U  I405;
    int (* I406)(void);
    int (* I407)(void);
    void * I408;
    void * I409;
    void * I410;
    U  I411;
    U  I412;
    U  I413;
    U  I414;
    U  I415;
    U  I416;
    char * I417;
    U  I418;
    U  * I419;
    U  I420;
    U  * I421;
    U  I422;
    U  I423;
    U  I424;
    U  I425;
    U  I426;
    U  I427;
    U  * I428;
    U  I429;
    U  I430;
    U  * I431;
    U  I432;
    U  I433;
    U  * I434;
    char * I435;
    U  I436;
    U  I437;
    U  I438;
    U  I439;
    U  * I440;
    U  * I441;
    U  I442;
    U  * I443;
    U  * I444;
    U  I445;
    U  I446;
    U  I447;
    U  I448;
    struct cosim_info * I449;
    U  I451;
    U  * I452;
    U  I453;
    void * I454;
    U  I455;
    U  * I456;
    U  I457;
    U  * I458;
    U  I459;
    U  I460;
    U  * I461;
    U  I462;
    U  * I463;
    U  I464;
    U  * I465;
    U  I466;
    U  I467;
    U  I468;
    U  I469;
    U  I470;
    U  I471;
    U  I472;
    U  I473;
    U  I474;
    U  * I475;
    U  * I476;
    void (* I477)(void);
    U  * I478;
    UP  * I479;
    struct mhdl_outInfo * I480;
    UP  * I482;
    U  I483;
    UP  * I484;
    U  I485;
    void * I486;
    U  * I487;
    void * I488;
    char * I489;
    int (* I490)(void);
    U  * I491;
    char * I492;
    char * I493;
    U  I494;
    U  * I495;
    char * I496;
    U  I497;
    struct regInitInfo * I498;
    UP  * I500;
    U  * I501;
    char * I502;
    U  I503;
    U  I504;
    U  I505;
    U  I506;
    U  I507;
    U  I508;
    U  I509;
    U  I510;
    UP  * I511;
    U  I512;
    U  I513;
    U  I514;
    U  I515;
    UP  * I516;
    U  I517;
    UP  * I518;
    U  I519;
    U  I520;
    U  I521;
    U  * I522;
    U  I523;
    U  I524;
    U  I525;
    U  * I526;
    U  * I527;
    UP  * I528;
    UP  * I529;
    void * I530;
    UP  I531;
    void * I532;
    void * I533;
    void * I534;
    void * I535;
    void * I536;
    UP  I537;
    U  * I538;
    U  * I539;
    void * I540;
    U  I541 :1;
    U  I542 :31;
    U  I543;
    U  I544;
    U  I545;
    int I546;
    U  I547 :1;
    U  I548 :1;
    U  I549 :1;
    U  I550 :29;
    void * I551;
    void * I552;
    void * I553;
    void * I554;
    UP  * I555;
    U  * I556;
    U  I557;
    char * I558;
    U  * I559;
    U  * I560;
    char * I561;
    int * I562;
    UP  * I563;
    struct etype * I564;
    U  I613;
    U  I614;
    U  I615;
    U  * I616;
    void * I617;
    U  I618;
    U  I619;
    void * I620;
    U  I621;
    U  I622;
    U  * I623;
    U  I624;
    U  * I625;
    U  I626;
    U  I627;
    U  * I628;
};
typedef struct pcbt {
    U  * I372;
    UP  I373;
    U  I374;
    U  I375;
    U  I376;
    U  I377;
    U  I378;
    U  I379;
} PCBT;
struct iptmpl {
    QIRD  * I702;
    struct vcs_globals_t * I703;
    void * I705;
    UP  I706;
    UP  I707;
    struct iptmpl * I698[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I886[256];
    struct _hsimPeriodL * I842;
} HsimPeriodL;
typedef struct {
    U   I888[2];
    U  I889 :1;
    U  I890 :1;
    U  I891 :8;
    U  I892 :8;
    U  I893 :8;
    U  I894 :4;
    unsigned long long I895;
    unsigned long long I896;
    unsigned long long I897;
    unsigned long long I898;
    unsigned long long I899;
    U  I900;
    U  I901;
    U  I902;
    U  I903;
    HsimPeriodL  * I904;
    HsimPeriodL  * I905;
    U  I906;
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I907;
    InstNum  I908;
    U  I850;
    scalar  I909;
    UB  I910;
    UB  I911;
    UB  I912;
    U  I913;
    U  I914;
    U  I915;
    U  I916;
    U  I917;
    HsimSignalMonitor  * I918;
    RmaTimeStamp64  I919;
    U  I920;
    RmaTimeStamp64  I921;
} HsimNodeRecord;
typedef struct {
    RP  I922;
    RP  I698;
} RmaIbfIp;
typedef struct {
    RP  I922;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I695;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RmaEblk  I695;
    RP  I923;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I695;
    RP  I924;
    RP  I923;
    vec32  I925;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I695;
    RP  I924;
    RP  I923;
    vec32   I743[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I695;
    RP  I924;
    RP  I923;
    scalar   I926[1];
} RmaAnySchedECg;
typedef struct {
    RP  I927;
} RmaRootCbkCg;
typedef struct {
    RP  I928;
} RmaRootVcdCg;
typedef struct {
    RP  I929;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I695;
    RP  I930;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I691 :30;
    U  I931 :1;
    U  I932 :1;
    vec32  I773;
    U  I933;
    RP  I934;
    RP  I935;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I941;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I633;
    RmaIbfPcode   I941[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I941;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I942;
    U  I943 :3;
    U  I944 :1;
    U  I945 :1;
    U  I946 :16;
} RmaNbaGateOfn;
typedef struct {
    NBS  I947;
    RmaIbfPcode  I942;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct {
    U  I5;
    U  iinput;
    RP  I950;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    RP  I950;
} RmaMacroStateUpdate;
typedef struct {
    U  I5;
    U  state;
    U  I951;
    U  * I952;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I953;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I953;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I695;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I695;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I695;
    RP  pcode;
    RP  pfn;
    scalar  I954;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I955;
    RP  I956;
    RP  I957;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I695;
    RP  pcode;
    U  I850;
    U   I684[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I5;
    RP  I772;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaGateDelay;
typedef struct {
    U  I5;
    RP  I772;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaGateBehavioralDelay;
typedef struct {
    U  I5;
    union {
        RP  I1100;
        RP  I1362;
        RP  I1375;
    } I747;
    RmaIbfPcode  I942;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I958;
    RmaIbfPcode  I942;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I942;
    RmaMps  I959;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I960;
    RmaIbfPcode  I942;
    RmaEblk  I733;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I942;
    RmaMpspNewCsdf  I961;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I961;
    RmaIbfPcode  I942;
} RmaMPPulseOptHybridDelay;
typedef struct _RmaBehavioralTransportDelay {
    U  I5;
    RP  I650;
    RmaTransEventHdr  I856;
    RP  I769;
    RmaIbfPcode  I942;
} RmaBehavioralTransportDelayS;
typedef struct {
    U  I5;
    U  I650;
    RmaTransEventHdr  I856;
    RP  I769;
    RmaIbfPcode  I942;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I650;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I962;
    U  I963;
    RmaTransEventHdr  I856;
    RP  I769;
    RmaIbfPcode  I942;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I962;
    U  I963;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I964;
    RmaTransEventHdr  I856;
    RP  I769;
    RmaIbfPcode  I942;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I964;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I772;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1362;
        RP  I1375;
    } I747;
    RmaIbfPcode  I942;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I772;
    RmaEblk  I695;
    RmaIbfPcode  I942;
} RmaPortDelay;
typedef struct {
    U  I5;
    RP   I965[(4)];
} RmaRtlXEdgesHdr;
typedef struct {
    U  I5;
    US  I966;
    US  I594;
    RP  I967;
    RP  I968;
    RP  I969;
} RmaRtlEdgeBlockHdr;
typedef struct {
    RP  I970;
    RP  I971;
} RemoteDbsedLoad;
typedef struct {
    RmaEblk  I695;
    US  I972;
    US  I594;
    U  I455;
    RP   I776[(4)];
    RP   I778[(4)];
    RemoteDbsedLoad   I973[1];
} RmaRtlEdgeBlock;
typedef struct TableAssign_ {
    struct TableAssign_ * I842;
    struct TableAssign_ * I763;
    U  I5;
    U  I975 :1;
    U  I976 :1;
    U  I977 :2;
    U  I978 :1;
    U  I667 :8;
    U  I594 :19;
    RP  ptable;
    RP  I953;
} TableAssign;
typedef struct {
    U  I5;
    RP  I763;
    RP  I979;
} RmaTableAssignList;
typedef struct {
    RP  I970;
} RmaWakeupListCg;
typedef struct {
    U  I980;
    U  I667;
    RmaTimeStamp   I981[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I982;
} RmaConditionsMdb;
typedef struct {
    RP  I842;
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I842;
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I993;
} RmaTcCoreConditional;
typedef struct {
    RP  I842;
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I993;
    RP  I994;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I842;
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I994;
    RP  I995;
    U  I996;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I998;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I993;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I993;
    RP  I994;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I994;
    RP  I995;
    U  I996;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I994;
    RP  I995;
    RP  I998;
    U  I996;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    RP  I993;
    RP  I998;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I983;
    RP  I690;
    U  I984;
    scalar  I946;
    scalar  I985;
    US  I986 :1;
    US  I987 :1;
    US  I988 :1;
    US  I989 :1;
    US  I990 :1;
    US  I991 :1;
    US  I992 :5;
    U  I999;
    RP  I1000;
    RP  I1001;
    RP  I993;
    RP  I1002;
    RP  I1003;
    RmaTimeStamp  I1004;
} RmaTcCoreNochange;
typedef struct {
    RP  I1005;
    RP  I842;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I982;
    RmaTimeStamp  I1006;
    scalar  I1007;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I842;
    RP  I982;
    RmaTimeStamp  I1006;
    scalar  I1007;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I1006;
    scalar  I1007;
    US  I946;
    RP  I994;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I842;
    RmaTimeStamp  I1006;
    scalar  I1007;
    US  I946;
    RP  I994;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I994;
    RP  I1008;
    U  I996;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I998;
    RP  I994;
    RP  I1008;
    U  I996;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I842;
    RP  I994;
    RP  I1008;
    U  I996;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I1009;
    U  I1010;
    FlatNodeNum  I1011;
    U  I850;
    U  I1012;
    U  I1013;
    RmaIbfPcode  I942;
    union {
        scalar  I1014;
        vec32  I1015;
        scalar  * I1016;
        vec32  * I1017;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I842;
    RP  I763;
    RP  I1018;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I1019;
    U  I1020 :1;
    U  I1021 :1;
    U  I1022 :1;
    U  I1023 :4;
    U  I594 :25;
    U  I1024;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1408;
        RmaSwitchGateInCbkListInfo  I2;
    } I664;
    RmaIbfPcode  I942;
} RmaSwitchGate;
typedef struct RmaNonEdgeLoadData1_ {
    US  I1025;
    scalar  val;
    scalar  I178 :4;
    scalar  I1026 :1;
    scalar  I1027 :1;
    scalar  I1028 :1;
    scalar  I1029 :1;
    RP  I776;
    RP  I1030;
    RP  I1011;
    RP  I1031;
    RP  I1032;
} RmaNonEdgeLoadData1;
typedef struct RmaNonEdgeLoadHdr1_ {
    UB  I1033;
    UB  I1034;
    RmaNonEdgeLoadData1  * I965;
    RmaNonEdgeLoadData1  * I763;
} RmaNonEdgeLoadHdr1;
typedef struct RmaChildClockProp_ {
    RP  I776;
    RP  I1035;
    RP  I1011;
    RP  pcode;
    scalar  val;
} RmaChildClockProp;
typedef struct RmaChildClockPropList1_ {
    RmaChildClockProp  * I965;
    RmaChildClockProp  * I763;
} RmaChildClockPropList1;
typedef struct {
    U  I5;
    U  I1036;
} RmaHDLCosimDUTGate;
struct clock_load {
    U  I178 :5;
    U  I179 :12;
    U  I180 :1;
    U  I181 :2;
    U  I182 :1;
    U  I183 :1;
    U  I184 :1;
    U  I185 :9;
    U  I186;
    U  I187;
    void (* pfn)(void * I189, char val);
};
typedef struct clock_data {
    U  I194 :1;
    U  I195 :1;
    U  I196 :1;
    U  I197 :1;
    U  I178 :5;
    U  I179 :12;
    U  I198 :6;
    U  I199 :1;
    U  I181 :2;
    U  I182 :1;
    U  I185 :1;
    U  I200;
    U  I201;
    U  I202;
    U  I186;
    U  I203;
    U  I204;
    U  I205;
    U  I206;
    U  I207;
} HdbsClockData;
struct clock_hiconn {
    U  I211;
    U  I212;
    U  I186;
    U  I181;
};
typedef struct _RmaDaiCg {
    RP  I1037;
    RP  I1038;
    U  I1039;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I1037;
    RP  I1040;
    RP  I1041;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I1042;
} RmaDaiOptCg;
struct futq_slot2 {
    U  I725;
    U   I726[32];
};
struct futq_slot1 {
    U  I722;
    struct futq_slot2  I723[32];
};
struct futq_info {
    U  I718;
    U  I719;
    struct futq_slot1  I720[32];
};
struct futq {
    struct futq * I708;
    struct futq * I710;
    RmaEblk  * I711;
    RmaEblk  * I712;
    U  I700;
};
struct sched_table {
    struct futq * I713;
    struct futq I714;
    struct hash_bucket * I715;
    struct hash_bucket * I717;
};
struct dummyq_struct {
    clock_struct  I1046;
    EBLK  * I1047;
    EBLK  * I1048;
    struct futq * I1049;
    struct futq * I1050;
    struct futq * I1051;
    struct sched_table * I1052;
    struct futq_info * I1054;
    U  I1056;
    U  I1057;
    U  I1058;
    struct millenium * I1059;
    EBLK  * I1061;
    EBLK  * I1062;
    EBLK  * I1063;
    EBLK  * I1064;
    EBLK  * I1065;
    EBLK  * I1066;
    EBLK  * I1067;
    EBLK  * I1068;
    EBLK  * I1069;
    EBLK  * I1070;
    EBLK  * I1071;
    EBLK  * I1072;
    EBLK  * I1073;
    EBLK  * I1074;
    EBLK  * I1075;
    EBLK  * I1076;
    EBLK  * I1077;
    EBLK  * I1078;
    MPS  * I1079;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_LPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I696;
    EBLK  * I1080;
    int I1081;
    struct _lqueue * I737;
} Queue;
typedef struct {
    EBLK  I1083;
    U  I1084;
    union {
        void * pHeap;
        Queue  * pList;
    } I664;
    Queue   I1085[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern FP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern UB  * expandedClkValues;
extern US   xedges[];
extern Qhdr  * lvlQueue;
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern UB  fNettypeIsForced;
extern UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern US  * edgeActionT;
extern unsigned long long * derivedClk;
extern U  fHashTableSize;
extern U  fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, UP* rtlFuncs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void doMpdCommon(MPS* pmps);
extern TimeStamp GET_DIFF_DELAY_FUNC(TimeStamp ts);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(UB *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void appendTransEventS(RmaTransEventHdr* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWLe32(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern U fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern void pushHsimRtnCtxt(void* pcode);
extern void popHsimRtnCtxt();
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvalRtlEdgeLoads(RmaRtlEdgeBlockHdr *phdr, US clkEdge, scalar clkVal, scalar prevClkVal, scalar val4,   scalar prevval4);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern void rmaScheduleGatedClockEdgeLoad(UB* p, US* ea, U fNonEdgeLoad, UB* plist, UB* pprevlist, scalar v);
extern void rmaRemoveNonEdgeLoads(UB* pcode);
extern void handlePCBs(UB* p, U i);
extern void markMasterClkOvaLists(U fdbs, RP p);
extern void rmaChildClockPropAfterWrite(UB* p);
extern void rmaSchedChildClockPropAfterWrite(UB* p, UB* pmasterList, UB val);
extern void HDLCosimProcessDUTInputChange(U inputId, void* val);
extern void rmaChangeListForMovedGates(UB clkVal, UB f10Edge, UB* subMasterVal, UB* plist, RP* p, U count);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  hsM_2_0__simv_daidir (UB  * pcode, scalar  val);
void  hsM_6_0__simv_daidir (UB  * pcode, scalar  val);
void  hsM_6_1__simv_daidir (UB  * pcode, scalar  val, U  I642, scalar  * I1110, U  did);
void  hsM_6_2__simv_daidir (UB  * pcode);
void  hsM_7_0__simv_daidir (UB  * pcode, scalar  val);
void  hsM_7_1__simv_daidir (UB  * pcode, scalar  val, U  I642, scalar  * I1110, U  did);
void  hsM_7_2__simv_daidir (UB  * pcode);
void  hsM_8_0__simv_daidir (UB  * pcode, scalar  val);
void  hsM_8_1__simv_daidir (UB  * pcode, scalar  val, U  I642, scalar  * I1110, U  did);
void  hsM_8_2__simv_daidir (UB  * pcode);
void  hsM_9_0__simv_daidir (UB  * pcode, scalar  val);
void  hsG_0 (struct dummyq_struct * I1092, EBLK  * I1093, U  I650);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

