./espresso/Makefile
./espresso/errtrap/Makefile
./espresso/errtrap/Makefile.old
./espresso/errtrap/Makefile.template
./espresso/espresso/Makefile.template
./espresso/espresso/Makefile
./espresso/espresso/Makefile.old
./espresso/mm/Makefile.old
./espresso/mm/Makefile
./espresso/mm/Makefile.template
./espresso/port/Makefile.old
./espresso/port/Makefile
./espresso/port/Makefile.template
./espresso/st/Makefile.old
./espresso/st/Makefile
./espresso/st/Makefile.template
./espresso/uprintf/Makefile.old
./espresso/uprintf/Makefile
./espresso/uprintf/Makefile.template
./espresso/utility/Makefile
./espresso/utility/Makefile.old
./espresso/utility/Makefile.template
./signature/Makefile
./signature/errtrap/Makefile
./signature/errtrap/Makefile.old
./signature/errtrap/Makefile.template
./signature/espresso/Makefile.template
./signature/espresso/Makefile
./signature/espresso/Makefile.old
./signature/mm/Makefile.old
./signature/mm/Makefile
./signature/mm/Makefile.template
./signature/port/Makefile.old
./signature/port/Makefile
./signature/port/Makefile.template
./signature/st/Makefile.old
./signature/st/Makefile
./signature/st/Makefile.template
./signature/uprintf/Makefile.old
./signature/uprintf/Makefile
./signature/uprintf/Makefile.template
./signature/utility/Makefile
./signature/utility/Makefile.old
./signature/utility/Makefile.template
